angelscript: use std::numeric_limits<uint64_t>::max() instead of UINT64_MAX
Otherwise it fails with:
/home/travis/build/supertuxkart/stk-code/lib/angelscript/source/as_string_util.cpp: In function ‘asQWORD asStringScanUInt64(const char*, int, size_t*, bool*)’:
/home/travis/build/supertuxkart/stk-code/lib/angelscript/source/as_string_util.cpp:189:28: error: ‘UINT64_MAX’ was not declared in this scope
/home/travis/build/supertuxkart/stk-code/lib/angelscript/source/as_string_util.cpp:216:29: error: ‘UINT64_MAX’ was not declared in this scope

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>